### ISSUE TITLE
Archived Teams in Planning Center Not Archived in Rock

### ISSUE THREAD

**Issue by jordangrogan** [9-Embers/Plugins#11]
**Affeced Plugin**
Which plugin does this bug affect?
PCO v2

**Describe the bug**
Archiving a Team in Planning Center Services does not archive the corresponding Group in Rock after running the Folder Import assistant again.

**To Reproduce**
1. Run the Folder Import Assistant upon installing the plugin.
2. Archive a Team in Planning Center Services.
3. Run the Folder Import Assistant again

**Expected behavior**
I would expect the corresponding PCO Marker Id group in Rock to be archived.

**Screenshots**
<img width="749" alt="Screenshot 2024-10-06 at 9 02 25 PM" src="https://github.com/user-attachments/assets/2e369cd1-b7fa-4ace-b9e8-27fcaf1368a4">
<img width="646" alt="Screenshot 2024-10-06 at 8 59 43 PM" src="https://github.com/user-attachments/assets/d9b04466-a0e4-4449-b955-72ce42be4c45">

**Comment by azturner** [comment]
v1.2.0 of the plugin will activate or inactivate groups in Rock based on whether the associated team is archived in Planning Center.
