### ISSUE TITLE
PCO v2: Sync History Operations Grid Pagination Links Do Not Work

### ISSUE THREAD

**Issue by jordangrogan** [9-Embers/Plugins#2]
**Affected Plugin**
PCO v2

**Describe the bug**
On the Sync History page, in the Operations grid, the pagination links (1, 2, 3...) do not work.

**To Reproduce**
1. Go to Sync History page
2. Choose a Sync History
3. In the Operations grid, click a page (1, 2, 3) or 5,000 items.

**Expected behavior**
The operations grid advances to the next page.

**Actual behavior**
Nothing happens. The grid does not advance to the next page.

**Screenshots**
<img width="1331" alt="Screenshot 2024-09-02 at 7 24 59 PM" src="https://github.com/user-attachments/assets/5722c8e3-1345-41fc-9a4e-cb963739f6cc">

**Additional context**
My grid has 3,706 operations / ops descriptions.
Switching to 500 operations does work. I cannot get the 5,000 button to show more.
Azure VM B4ms
Azure SQL Standard S2: 50 DTUs

**Comment by azturner** [comment]
Fixed here (not yet released)
https://github.com/9-Embers/Plugin_CommonSync/commit/2c645d7f1cf36bb436a0ee65c97a5b49121cc4a4
